### ISSUE TITLE
Dibi Fluent: DELETE x FROM y

### ISSUE THREAD

**Issue by knyttl** [dg/dibi#151]
Dibi Fluent is not able to handle constructs like:

     $db->delete('x')->from('y')

It should generate query:

     DELETE x FROM y

It generates instead:

     DELETE FROM x, y 

This is completely valid query, the reasons can be seen here: http://stackoverflow.com/questions/1980738/sql-delete-with-join-another-table-for-where-condition

**Comment by dg** [comment]
Try ` $db->delete('y')->delete('x')`

**Comment by knyttl** [comment]
It does not look very user friendly nor logic :/

**Comment by dg** [comment]
Yes, but it is very rare use case.

**Comment by knyttl** [comment]
Great argument.

**Comment by dg** [comment]
I mean that fix is too complicated, so it does not make sense to do it for rare use case. 

`$db->delete()` simply means `$db->deleteFrom()`, so `$db->delete('x')->from('y')` is in fact `$db->deleteFrom('x')->from('y')` and result is therefore expected. But you can avoid `delete()` this way:

```php
$db->command()->delete('x')->from('y'); // DELETE x FROM y
```
