### ISSUE TITLE
use mysqli as default driver instead of mysql

### ISSUE THREAD

**Issue by iinfo-dev-mk** [dg/dibi#156]
Mysql ext is deprecated in PHP 5.5.+ and will not be available in major future version of PHP. It throws deprecated error now, but it's hidden because of usage of @ - shut up operator - in dibi mysql driver.

It's much better use mysqli as default driver.  It's BC break but small. Place for change -
https://github.com/dg/dibi/blob/master/dibi/libs/Dibi.php#L71

**Comment by JanTvrdik** [comment]
@dg Any thoughts?

**Comment by dg** [comment]
I think that `defaultDriver` is a historical relic and should be removed at all.

**Comment by iinfo-dev-mk** [comment]
It can be, but it's huge BC break, much bigger then switching to another default driver. I don't see many reasons for removing, default driver is useful case, there is mostly one type of db system in the small and middle sized companies and so all connections in all projects in such companies can benefits from default driver pattern.
