### ISSUE TITLE
escapeLike issue on postgre

### ISSUE THREAD

**Issue by cdujeu** [dg/dibi#159]
Hi David, 

First of all, thanks for your great work. As you maybe already know, Dibi is our historical ORM for the Pydio project, and we love it: doing the job efficiently, and very lightweight (we embed the minified version).
I'm not totally sure this is an issue, or maybe a postgre config or version problem, I must admit I'm not a PG expert. We are encountering an issue with LIKE queries containing an underscore, and I happened to fix this by changing the escapeLike function of the PG driver to replace '_' by \\_ instead of \\\\_ . 
Which gives for the escapeLike function
```
function escapeLike($value,$pos){
    $value=pg_escape_string($this->connection,$value);
    $value=strtr($value,array('%'=>'\\%','_'=>'\\_'));
    return($pos<=0?"'%":"'").$value.($pos>=0?"%'":"'");
}
```
Do you know if it's a bug or something wrong on my -db- side? 
Using PG 9.3 BTW.

Cheers
Charles

**Comment by milo** [comment]
The PostgreSQL [specifies](http://www.postgresql.org/docs/9.1/static/functions-matching.html) two special chars in LIKE pattern: the `_` and `%`. So, this two must be escaped in user input.

Problem may be the [`standard_conforming_strings`](http://www.postgresql.org/docs/9.3/interactive/runtime-config-compatible.html#GUC-STANDARD-CONFORMING-STRINGS) directive.

Imho, the right solution is the:
```
return 'E' . ($pos <= 0 ? "'%" : "'") . $value . ($pos >= 0 ? "%'" : "'");
```
It should work with any PostgreSQL setting. Can you confirm that?

**Comment by JanTvrdik** [comment]
Does this directly affect only LIKE?

**Comment by cdujeu** [comment]
hi guys
sorry I was not available yesterday.
from my initial debugging / testing, escaping with \\\\ was finally executing a request with eg. \\_ instead of \_
That's why I changed the line.
I'll try with your last commits and tell you. 
And yes it was affecting only like, as _ is a specific wildcard used in LIKE queries.
-c

**Comment by milo** [comment]
@cdujeu I hope it is solved by #160

**Comment by cdujeu** [comment]
@milo currently using the minified version, could you generate such a file including your latest commits? Will be more straightforward to test... thx in advance

**Comment by milo** [comment]
@cdujeu Unfortunately not. @dg has the minifier. The `/dibi` only directory and the `dibi/dibi.php` loading should work...

**Comment by cdujeu** [comment]
@dg any quick help on this ;-) ?

**Comment by cdujeu** [comment]
Confirmed. Thank you so much to all for your reactivity.
