### ISSUE TITLE
named conections are deprecated

### ISSUE THREAD

**Issue by peacemaster** [dg/dibi#161]
Why you refused named conections?

Are there any alternative ways to use them?

**Comment by dg** [comment]
How are you using them?

**Comment by peacemaster** [comment]
I connect to more then one database, and using this connections in the code

**Comment by fprochazka** [comment]
Isn't this better?

```php
$localDb = new \DibiConnection(array('driver' => 'mssql', 'host' => 'localhost1', 'username' => 'root', 'password' => 'pass'));
$mainDb = new \DibiConnection(array('driver' => 'mssql', 'host' => 'localhost2', 'username' => 'root', 'password' => 'pass'));
```

**Comment by dg** [comment]
To create more connection and to use getConnection() is (relatively) OK, it can be reverted. Problematic is `activate()`.

**Comment by JanRossler** [comment]
+1 I'd also like to keep the ability to create more connections and access them with getConnection($name).

**Comment by vojtech-dobes** [comment]
"The feature isn't there and it's not gonna be there." :) No really, creating more instances doesn't make `DibiConnection` *also* a registry of its own kind, which is much cleaner architecture.
