### ISSUE TITLE
Nefunguje v debug baru databázový profiling

### ISSUE THREAD

**Issue by stepanpernica** [dg/dibi#162]
V DibiConnection.php chyba na řádku 114 - podle mě nemá být negace na Tracy panel. Bez vykřičníku funguje správně.

			if (!interface_exists('Tracy\IBarPanel') && interface_exists('Nette\Diagnostics\IBarPanel') && class_exists('DibiNettePanel')) {
				...
				$panel->register($this);
			}

**Comment by dg** [comment]
Did you register it to Nette via extension? https://github.com/dg/dibi/blob/master/dibi/bridges/Nette-2.2/config.sample.neon

**Comment by stepanpernica** [comment]
Sorry, my mistake. I use old code syntax with dibi::connect
