### ISSUE TITLE
DibiFluent warning with oracle driver on $fluent->count();

### ISSUE THREAD

**Issue by alesculek** [dg/dibi#172]
Using dibi with oracle driver:
$fluent = $dibi->select('*')->from('scheme.table');
$fluent->count();

Getting warning:
oci_execute(): ORA-00933: příkaz SQL není řádně ukončen

Native query looks like this:
SELECT COUNT(*) FROM ( SELECT * FROM "scheme"."table" ) AS "data"

There is problem with: AS "data"
composer: "dibi/dibi": "~2.3@dev"

if you need to include more information then please reply.

**Comment by dg** [comment]
This works? `SELECT COUNT(*) FROM ( SELECT * FROM "scheme"."table" ) "data"`

**Comment by milo** [comment]
@dg It works without `AS` with Oracle `9.2` and `11.2.`
