### ISSUE TITLE
MsSQL returned value of datetime column can not be normalized, no chance to get DateTime

### ISSUE THREAD

**Issue by matak** [dg/dibi#180]
if you select datetime column mssql returns

something like this

Jun 17 2015 12:00:00:000AM

but normalize function will not create DateTime object bcs

https://github.com/dg/dibi/blob/master/dibi/libs/DibiResult.php#L508

this is not true

(int) $value !== 0

if you want to get from mssql date format like this 2015-06-17 00:00:00

you need to use this

CONVERT(VARCHAR(19), d.Datum, 120) as Datum,

in your query, but this will be detected like string not datetime so again DateTime object will not be created

**Comment by milo** [comment]
AFAIK, default date format depends on session language. You can change the session language or maybe set the [DATEFORMAT](https://msdn.microsoft.com/en-us/library/ms189491.aspx).

**Comment by bckp** [comment]
This is issue of MsSQL, not Dibi by my opinion. To get DateTime object in PHP from DIBI, youshould use CONVERT in QUERY and then setType function of Dibi (or asDateTime on Dibi\Row)

```php 
setType('column', \Dibi::DATETIME)
```

See this
https://api.dibiphp.com/3.0.1/source-Dibi.Row.php.html#31-47
https://api.dibiphp.com/3.0.1/source-Dibi.Result.php.html#537-547

**Comment by bckp** [comment]
@dg close please, this is not bug

**Comment by dg** [comment]
Probably condition can be improved to accept this format.

**Comment by bckp** [comment]
@dg Thanks 👍
