### ISSUE TITLE
loadFile does not show sql errors

### ISSUE THREAD

**Issue by stanislavdavid** [dg/dibi#182]
Hello, 
when I try to load faulty sql file with loadFIle

    dibi::loadFile('dump.sql');
Dibi does not show any sql error. There is not even any info in the logs.

**Comment by JanTvrdik** [comment]
loadFile is optimized for performance, not reliability. Can you post an example of the invalid SQL which you would expect to throw an exception?

**Comment by dg** [comment]
ping @stanislavdavid

**Comment by dg** [comment]
Unable to verify
