### ISSUE TITLE
Invalid combination of type DateTime and modifier %dt

### ISSUE THREAD

**Issue by hubipe** [dg/dibi#198]
When I try to update data with modifier `\Dibi\Type::DATETIME`, `Dibi\Exception` is thrown with message
     
    SQL translate error: Invalid combination of type DateTime and modifier %dt.

In my opinion, there is inconsistency between `Dibi\Translator` and `Dibi\Type`. Before upgrade to 3.0, the modificators were the same, after upgrade mismatch between these operators appeared.

Sample data I was trying to save:

    array (1)
    0 => array (9)
        0 => "UPDATE" (6)
        1 => "%n" (2)
        2 => "objednavky_objednavka" (21)
        3 => "SET" (3)
        4 => "%a" (2)
        5 => array (2)
            "last_money_xml_import_id%sN" => "FEC42756-BA20-45F4-AB2D-38901B095AF7" (36)
            "last_money_xml_import_at%dt" => DateTime #835e
                date => "2015-11-30 08:40:25.000000" (26)
                timezone_type => 3
                timezone => "Europe/Berlin" (13)
        6 => "WHERE" (5)
        7 => "id = %i" (7)
        8 => 498

**Comment by dg** [comment]
I think that modifier `%dt` never existed.

**Comment by hubipe** [comment]
But it exists now.
I have a metadata class, which reads data types of table columns in MSSQL database and store it in cache. So when it reads, that column1 is type of DATETIME2, it stores \Dibi\Type::DATETIME as column type. So whenever I make update on an entity, it automatically append this data type as a modifier to updated columns data (it adds percent sign and column type after column name in insert/update queries) — like in sample data[0][5].

The thing is, that before update to the version 3.0, the constant value for DATETIME was 't', now it is 'dt', but in insert/update queries, Dibi\Translator doesn't know modifier 'dt' and it thinks, thaht 't' is DATETIME, instead of just TIME. That's the confusing part

**Comment by dg** [comment]
Still I do not understand the connection between modifier like `%xyz` and constant `Type::XYZ`.

**Comment by hubipe** [comment]
Until 3.0 update, I thought, that Type constants is subset of % modifiers. So whenever I made update, I basically wrote `'updated_column%' . \dibi::TYPE_DATETIME`, so if the modifiers would change in the future version, I wouldn't have to change all the literals in my code.
I see now, that this asuamption might have been wrong...
So wouldn't be better, if dibi would preserve this behaviour? That %dt would mean datetime, %t time and %d date?
