### ISSUE TITLE
Firebird and EXPLAIN 

### ISSUE THREAD

**Issue by ondrej-tuhacek** [dg/dibi#203]
Firebird does not have the EXPLAIN command, but Dibi Tracy panel expects it to exist and so it fails at any SQL query. The only way to currently stop this, is set "profiler: false" in config.neon in Nette configuration of Dibi extension.

It would be nice if we could pass the arguments into Tracy Panel in DibiExtension22.php from configuration ... so we can call it like

		if ($useProfiler) {
			$panel = $container->addDefinition($this->prefix('panel'))
				->setClass('Dibi\Bridges\Tracy\Panel', [FALSE]);
			$connection->addSetup([$panel, 'register'], [$connection]);
		}

instead of

		if ($useProfiler) {
			$panel = $container->addDefinition($this->prefix('panel'))
				->setClass('Dibi\Bridges\Tracy\Panel');
			$connection->addSetup([$panel, 'register'], [$connection]);
		}

without arguments ...

The __construct of Panel class has first argument $explain which defaults to TRUE and cannot be overriden.

	public function __construct($explain = TRUE, $filter = NULL)
	{
		$this->filter = $filter ? (int) $filter : Event::QUERY;
		$this->explain = $explain;
	}

**Comment by milo** [comment]
Keynote for PR https://github.com/dg/dibi/commit/aac83ba849d425744c4be50c70d72a65a1a7505e.

**Comment by ondrej-tuhacek** [comment]
Thanks!
