### ISSUE TITLE
MS SQL support on linux (dibi 3.0)

### ISSUE THREAD

**Issue by soukiii** [dg/dibi#205]
Dibi 3.0 zrušilo MySQLDriver a místo něj používá SqlSrv kvůli nepodpoře na 5.4+.

Extension mssql je ale normálně dostupný i v PHP 5.6 na linuxu a zmínka o nepodpoře v dokumentaci se týká jen windows. Naopak SqlSrv je dostupný pouze pro windows.

Nahrazením tak zmizela možnost připojit se k MS SQL z linuxu.

Má to nějaký důvod nebo to vzniklo jen kvůli trochu nejasnému popisu v dokumentaci PHP?

**Comment by dg** [comment]
Měl jsem za to, že to od PHP 5.4 nefunguje nikde.

**Comment by soukiii** [comment]
Používáme ho v 5.6 s dibi 2. Je vidět třeba tady v repozitáři: http://rpms.famillecollet.com/enterprise/6/php56/x86_64/repoview/development.languages.group.html
Není dostupný pro PHP7, ale to není ani SqlSrv (pro linux)

Mám zkoušet převést původní MySQLDriver pro dibi 3 nebo to bylo řešené nějakou automatikou?

**Comment by dg** [comment]
Revertnul jsem to https://github.com/dg/dibi/commit/8a7dbcba861087b54215c9c9326909ac826ec814

**Comment by soukiii** [comment]
Paráda!

**Comment by soukiii** [comment]
Jen doplním, že v PHP 7 na linuxu není ani mssql a ani sqlsrv - zase je tam ale pdo_dblib, takže v dibi jde krásně použít PDO driver.
