### ISSUE TITLE
FirebirdDriver.php - escapeIdentifier

### ISSUE THREAD

**Issue by ondrej-tuhacek** [dg/dibi#207]
Hello,

in the "Drivers/FirebirdDriver.php" there is:

```
	public function escapeIdentifier($value)
	{
		return $value;
	}
```

but in Firebird identifiers are escaped by quotation marks.
This is probably a bug.

Consider the following query:

```
SELECT * FROM LANGUAGES WHERE DEFAULT = 1
```

where DEFAULT is also a Firebird keyword so it needs to be properly escaped like:
```
SELECT * FROM "LANGUAGES" WHERE "DEFAULT" = 1
```

**Comment by dg** [comment]
Could you send PR?

**Comment by ondrej-tuhacek** [comment]
PR #208
