### ISSUE TITLE
Connect sqlsrv php7 

### ISSUE THREAD

**Issue by rumcais** [dg/dibi#211]
Po přechodu z php 5.6 na php7 mám chybovou hlášku Dibi\DriverException: Invalid value type for option Database was specified.  String type was expected. Pokud odstraním pointer v sqlsrvDriver na řádku 75   $options =  $config['options']; tak to běží. Díky M.

**Comment by castamir** [comment]
@dg is there any possibility to test Sql Server also with php7 on AppVeyor? Not just because of this issue, but there is a brand new sqlsrv extension for php7 [comming out](https://github.com/Azure/msphpsql/releases)

**Comment by dg** [comment]
@castamir done https://ci.appveyor.com/project/dg/dibi

**Comment by castamir** [comment]
@dg great! 

I'm going to fix php7 compatibility and test it also on my own apps.

**Comment by castamir** [comment]
As @rumcais said, a simple change and everything seems to work.

But AppVeyor for php7 throws a warning on no longer supported mysql driver. Removing it from php.ini and database.appveyor.ini will also affect mysql driver test for php5...
