### ISSUE TITLE
BC break: Row doesn't support array property insertion

### ISSUE THREAD

**Issue by iinfo-dev-mk** [dg/dibi#217]
Because Dibi\Row in 3.0.x has the magic __get it breaks adding new array property into row dynamically

```php
$row = new Dibi\Row(["value1"]);
$row->newArray[] = "value2";
```
It produces two errors:
- PHP User Notice: Attempt to read missing column 'newArray'
- PHP Notice: Indirect modification of overloaded property Dibi\Row::$newArray has no effect

and nothing is set.

Common case for $row->newArray[] is inserting m:n related things e.g. for list of t-shirts, insert dynamically list of possible colours into each one $tShirt->colours[] = $color; This cases produces tons of previously mentioned notices because it's called in loop and code doesn't work. 

There is workaround 

    $row->newArray = []; 
    $row->newArray[] = "value2";

nevertheless  consider remove __get because
- it produces tons of notices, it's commonly used in loops
- only new benefit for __get is helping avoiding typos, which is questionable, works only in some cases and PHP itself produces sufficient notice without any __get

If you don't want to remove __get, don't fix it with reference (&__get) please. 
And definitely updates release notes for 3.0.0 with mentioned BC break please, it helps the others a lot.

**Comment by dg** [comment]
I don't wan't to remove __get, because suggestions is useful feature. So I added note to release notes https://github.com/dg/dibi/releases/tag/v3.0.0.
