### ISSUE TITLE
Row: isset produces notices about non existed property

### ISSUE THREAD

**Issue by iinfo-dev-mk** [dg/dibi#218]
```php
$row = new Dibi\Row(["foo-bar"]);
if (!isset($row->foo->bar)) {
  echo "property foo doesn't exist";
}
```
Produces notice PHP User Notice: Attempt to read missing column 'foo'. 
:-0
There mustn't be any such notice for isset, empty usage.
It's also BC break, in 2.x it worked without any notice.

**Comment by dg** [comment]
Seems like PHP bug, can you report it? https://3v4l.org/8AQQh

Workaround: `if (!isset($row->foo, $row->foo->bar)) {`

**Comment by iinfo-dev-mk** [comment]
Hm, maybe, I have created https://bugs.php.net/bug.php?id=72056.
But your implementation for __get in Dibi\Row only for producing better error message isn't very relevant case for __get and brings more BC breaks and complications than benefits for us.

**Comment by dg** [comment]
It's because you use Row in the way that I didn't count with. The question is whether it is often the case and `Row::__get` should be removed or it is rare case and `Row::__get` is useful for majority. I really don't know.

**Comment by Ciki** [comment]
I don't know if it's common use case but I use it like @iinfo-dev-mk does as well

**Comment by iinfo-dev-mk** [comment]
Php bug is fixed! You can change fix it (for php 7+) also.

**Comment by dg** [comment]
Great!
