### ISSUE TITLE
Row: isset for chaning properties doesn't work

### ISSUE THREAD

**Issue by iinfo-dev-mk** [dg/dibi#219]
See #218, mentioned PHP bug https://bugs.php.net/bug.php?id=72056 is fixed, you can fix this also (for php 7.0.6+)

**Comment by iinfo-dev-mk** [comment]
Or maybe php upstream solves it completely :)

**Comment by iinfo-dev-mk** [comment]
Be aware the there is fundamental change in 7.0.6 in __isset and  __get precedence call, which can have huge impact on all descendants of your magical objects with implemented __isset. See https://bugs.php.net/bug.php?id=72223

**Comment by dg** [comment]
218 is fixed, isn't it?

**Comment by iinfo-dev-mk** [comment]
No it it isn't. It still produces notice. But your mentioned example in 218 works fine in PHP 7.0.6.

And be aware of new behaviour of __isset and __get also for your magic stuff in other projects like nette/object etc.

P.S. Sorry, I really hate __magic PHP stuff as well as your __magic which are built on these. Magic on Magic => not positive double magic, which can save time, but doubled time for fixing things which can live simple without any magic, ugh.

**Comment by dg** [comment]
So send PR and fix it.

**Comment by iinfo-dev-mk** [comment]
I will wait how PHP core devs will deal with mentioned complaint

**Comment by dg** [comment]
When proposed example works, it is fixed, or not? I really dont know what else to do.

**Comment by iinfo-dev-mk** [comment]
218 isn't fixed even with bug fix in PHP 7.0.6.  I think it's necessary to implement __isset in Dibi\Row, but I think waiting is better now.  New call precedence for magic __get and __isset introduces as bug fix in 7.0.6 produces many new errors, when this new call precedence is used for your "strict" object descendants. 
So I'll wait what php core devs will make with this and what will be final state. Most likely nothing will change, there are 2 or 3 bug reports for this newly introduced BC break as I know. Then I'll try to prepare PR.
I think it's not so critical, because your workaround mentioned in 218 is sufficient.

**Comment by iinfo-dev-mk** [comment]
It seems that PHP users are satisfied with change in __isset/__get. Same for Nette, Dibi users. I was definitely wrong with the possible impact. So you can close this one.
