### ISSUE TITLE
DibiFluent no longer supports aplying both offset and limit using a single limit() call (potential BC break)

### ISSUE THREAD

**Issue by tobice** [dg/dibi#223]
We were using the following construct to apply limit and offset on a fluent object:

```
$fluent->limit("%i, %i", $offset, $limit);
```

After updating to Dibi 3.x (from 2.3.2), this construct causes Dibi to append `LIMIT 0` to the end of the query which will then obviously return no results.

The proper way is to specify limit and offset separately using dedicated magic methods:

```
$fluent->offset($offset)->limit($limit);
```

This should be probably mentioned in the Release Notes.

**Comment by dg** [comment]
Added, thanks
