### ISSUE TITLE
Column alias containing dot has wrong quotation marks

### ISSUE THREAD

**Issue by radekdostal** [dg/dibi#224]
Is it error or feature?
If column alias contains the dot char, it has wrong quotation marks. For example:

```php
->select('[no]', '[Č. p.]')
// or ->select('[no]')->as('[Č. p.]')
// or ->select('[no]')->as('%n', 'Č. p.')
```
produces

```php
`no` AS `Č`.` p`.``
```

which ends with SQL error.

Workaround:

```php
->select('[no]')->as('"Č. p."')
```

produces

```php
`no` AS 'Č. p.'
```

**Comment by dg** [comment]
This cannot be fixed because it is intentional.
