### ISSUE TITLE
DibiDateTime is unserializable in version 3.0.0+

### ISSUE THREAD

**Issue by ZZromanZZ** [dg/dibi#226]
When magic method __wakeup() was [removed](https://github.com/dg/dibi/commit/3e010c0f4ddfb41887db5c5ceb18fd532dcb486f) in favor to drop support for <PHP 5.4, there left serialized property "fix" which is now unnsecesary but causes FatalError (_Invalid serialization data for DateTime object_) when DibiDateTime was serialized earlier and is unserialized now.

I suggest to put back function __wakeup() to preserve back compatibility.

**Comment by ZZromanZZ** [comment]
This helped in \Dibi\DateTime:
```php
public function __wakeup()
{
 	if (isset($this->fix[1])) {
 		$this->__construct($this->fix[0], new \DateTimeZone($this->fix[1]));
 	} else {
 	    $this->__construct($this->fix[0]);
  	}
	unset($this->fix);
 }
```

I can prepare MR, if there is now problem with this solution.

**Comment by dg** [comment]
Yes, send pr
