### ISSUE TITLE
Datetime BETWEEN wrong fetch

### ISSUE THREAD

**Issue by Dreiser** [dg/dibi#234]
I possibly found bug when using BETWEEN (or timestamp >= %t AND `timestamp` <= %t) on timestamp column.

If I run same fluent with test() and then execute directly in database, it return rows. Hovewer if I change test() to fetchAll() result count is 0. If I remove one of sides (>=, <=) it works fine. I am 100% sure that between condition is met. 

BILL::RECEIVED is timestamp, $receivedFrom and $receivedTo are instances of DibiDateTime. Casting in SQL to same type do not help either.

// array(0) {}
var_dump($this->getTable()
    ->where([
        ['%n BETWEEN %t AND %t', Bill::RECEIVED, $receivedFrom, $receivedTo],
        ['%n = %i', Bill::BRANCH_ID, $branchId],
        ['%n = %f', Bill::AMOUNT, $amount]
     ])
     ->fetchAll());
// After manual execution rows are returned
$this->getTable()
        ->where([
            ['%n BETWEEN %t AND %t', Bill::RECEIVED, $receivedFrom, $receivedTo],
            ['%n = %i', Bill::BRANCH_ID, $branchId],
            ['%n = %f', Bill::AMOUNT, $amount]
        ])
        ->test();

**Comment by alesculek** [comment]
Which driver? And can you paste generated sql (string)$fluent?

**Comment by Dreiser** [comment]
Sure. It is MySQL driver.
(string)$fluent is same as $fluent->test():
SELECT * FROM `bill` WHERE (`received` BETWEEN '2016-03-02 08:30:03' AND '2016-03-02 08:40:03') AND (`branch` = 5) AND (`amount` = 467)

Just in case it matter:
received is timestamp
branch is int (foreign key)
amount is decimal(11,2)

Weird is that I run this select on about 17500 different cases (with different WHERE conditions) and few of them (about 40) actually return something. I do not know if it return right rows in that cases.

**Comment by Dreiser** [comment]
OK so I maybe found reason. Now I'm not sure if it's bug or wanted behaviour.

If I search for row in database, time is fine. If I print that timestamp in PHP, time is shifted +1 hour - wrong timezone I guess. But even if it's little bit confusing, Dibi can't change this I guess. So issue seems closed for me. Sorry for false alert :)
