### ISSUE TITLE
Visibility modifier of function Dibi\Connection::translateArgs()

### ISSUE THREAD

**Issue by chvilalukas** [dg/dibi#237]
Please change visibility modifier of function Dibi\Connection::translateArgs() and variable $this->translator in the same class to protected. We need to create custom modification of translator and without this modification it is not possible. Thank you.

Sorry for my English...

**Comment by JanTvrdik** [comment]
Could you elaborate on what you intend to change?

**Comment by chvilalukas** [comment]
Currently we use dibi, which we in the class “Translator” have added modifier %mm (engineered variant of modifier %m). But at the same time we want to use “Composer”, so customizing the class is not an option.
When I look into class code of “Translator”, it should not be a problem to write a class inheriting from classes “Translator” and help her supply that modifier. The problem is that in the class “Connection” is not how the class inheriting from “Translator” pass. Maybe instead of editing of the visibility It would be enough to add functionality with which it would be possible to set a different translator.
