### ISSUE TITLE
$result->fetchAll() will return array data without class object?

### ISSUE THREAD

**Issue by jerrychen1013** [dg/dibi#240]
Hi David,

It's a strange situation that fetchAll should return array data set as I saw in documentation.
But why I got the result as below?

`Dibi\Row::__set_state(array( 'word' => 'good', 'weight' => -2, ))`

I thought it should return `array( 'word' => 'good', 'weight' => -2, )`.

Do I misunderstand fetchAll ?

Thank you

**Comment by milo** [comment]
It returns array of Dibi/Row objects.

**Comment by JanTvrdik** [comment]
@jerrychen1013 If you want to received array of arrays you need to call `$result->setRowClass(NULL)`

**Comment by jerrychen1013** [comment]
@JanTvrdik 
It works and return array without object includes.
Thank you.
I thought it may help me to reduce one foreach step, but I realized it's no difference to change the type in my project after that. Woops~
