### ISSUE TITLE
insert json to DB and Translator.php error happened.

### ISSUE THREAD

**Issue by jerrychen1013** [dg/dibi#241]
Hi guts,

When insert json string to MSSQL, dibi shows exception as below:

`Fatal error: Uncaught Dibi\PcreException: Unknown error. in C:\wamp64\www\project\vendor\dibi\dibi\src\Dibi\Translator.php:113
Stack trace:
#0 C:\wamp64\www\project\vendor\dibi\dibi\src\Dibi\Connection.php(299): Dibi\Translator->translate(Array)
#1 C:\wamp64\www\project\vendor\dibi\dibi\src\Dibi\Connection.php(234): Dibi\Connection->translateArgs(Array)
#2 C:\wamp64\www\project\app\CN2TW.php(927): Dibi\Connection->query(Array)
#3 C:\wamp64\www\project\app\CN2TW.php(493): CN2TW->queryWords(Array)
#4 C:\wamp64\www\project\app\CN2TW.php(455): CN2TW->updateNewsContent(Array, Array)
#5 C:\wamp64\www\project\app\CN2TW.php(27): CN2TW->updateEmotionScore()
#6 C:\wamp64\www\project\app\CN2TW.php(6536): CN2TW->__construct()
#7 {main}
  thrown in C:\wamp64\www\project\vendor\dibi\dibi\src\Dibi\Translator.php on line 113`

**When checked the Translator.php line 113, it seems have preg error,** 

$sql[] = substr($arg, 0, $toSkip)
. preg_replace_callback('/(?=[`[\'":%?])(?:`(.+?)`|\[(.+?)\]|(\')((?:\'\'|[^\'])*)\'|(")((?:""|[^"])*)"|(\'|")|:(\S*?:)([a-zA-Z0-9._]?)|%([a-zA-Z~][a-zA-Z0-9~]{0,5})|(\?))/s',
							[$this, 'cb'],
							substr($arg, $toSkip)

**It already spent me several hours to solve this problem, even transferred to serialize(), the same exception happened. Does anyone have the idea about it?**

Thank you!

**My sql statement is as below:**
`UPDATE articles 
                     SET score        = 61.04 
                        ,score_detail = '[{"\u53c3\u62dc":{"freq":1,"weight":2}},{"\u80af\u5b9a":{"freq":1,"weight":2}},{"\u5e0c\u671b":{"freq":1,"weight":2}},{"\u4e0d\u4fbf":{"freq":1,"weight":-2}},{"\u4e0d\u65b7":{"freq":1,"weight":-2}},{"\u707d\u5bb3":{"freq":2,"weight":-3.27}},{"\u554f\u984c":{"freq":2,"weight":-1.97}},{"\u6700\u4f4e":{"freq":1,"weight":-2}},{"\u640d\u5931":{"freq":1,"weight":-1.95}},{"\u640d\u5bb3":{"freq":2,"weight":-1.95}},{"\u5287\u70c8":{"freq":1,"weight":-2.71}},{"\u5287\u70c8\u7684":{"freq":1,"weight":-0.26}},{"\u66b4\u96e8":{"freq":1,"weight":-2}},{"\u885d\u64ca":{"freq":3,"weight":-2.97}},{"\u907f\u514d":{"freq":1,"weight":1.45}},{"\u56b4\u91cd":{"freq":2,"weight":-1.8}},{"\u9a5a\u4eba":{"freq":1,"weight":-2}},{"\u624d\u80fd":{"freq":1,"weight":2.56}},{"\u5929\u7136":{"freq":2,"weight":1.59}},{"\u7531\u8877":{"freq":1,"weight":2}},{"\u5408\u4f5c":{"freq":1,"weight":2}},{"\u5b89\u5168":{"freq":3,"weight":2.07}},{"\u52aa\u529b":{"freq":1,"weight":-2.87}},{"\u6539\u5584":{"freq":1,"weight":2.65}},{"\u9632\u6c34":{"freq":1,"weight":2}},{"\u4fdd\u8b77":{"freq":1,"weight":0.75}},{"\u5bb9\u6613":{"freq":1,"weight":2.1}},{"\u7279\u5225":{"freq":2,"weight":2}},{"\u767c\u5c55":{"freq":1,"weight":2.73}},{"\u9032\u6b65":{"freq":1,"weight":2.73}},{"\u6a5f\u6703":{"freq":1,"weight":1.02}},{"\u7a4d\u6975":{"freq":1,"weight":1.79}},{"\u98b1\u98a8":{"freq":3,"weight":-1.66}},{"\u7522\u696d":{"freq":1,"weight":0.3}},{"\u751f\u6d3b":{"freq":2,"weight":2.27}},{"\u77ac\u9593":{"freq":1,"weight":0.76}},{"\u5c40\u90e8":{"freq":1,"weight":0.11}},{"\u5c40\u90e8\u5730":{"freq":1,"weight":0.11}},{"\u4eba\u6c11":{"freq":2,"weight":2.33}},{"\u6c11\u773e":{"freq":1,"weight":2.33}},{"\u6a5f\u95dc":{"freq":1,"weight":0.55}},{"\u6642\u671f":{"freq":1,"weight":0.17}},{"\u54c1\u8cea":{"freq":2,"weight":0.3}},{"\u8868\u9054":{"freq":2,"weight":1.95}},{"\u9810\u9632":{"freq":1,"weight":2.29}},{"\u4fdd\u96aa":{"freq":2,"weight":2.07}},{"\u4e00\u76f4":{"freq":1,"weight":-0.26}},{"\u7bc4\u570d":{"freq":2,"weight":0.33}},{"\u5f37\u8abf":{"freq":1,"weight":-2.91}},{"\u884c\u7a0b":{"freq":1,"weight":2.1}},{"\u8655\u7406":{"freq":2,"weight":2.36}},{"\u8996\u5bdf":{"freq":1,"weight":0.78}},{"\u6025\u65bc":{"freq":1,"weight":-0.19}},{"\u73fe\u91d1":{"freq":3,"weight":3.37}},{"\u5167\u5bb9":{"freq":1,"weight":0.55}},{"\u6cbb\u7406":{"freq":1,"weight":-1.2}},{"\u7d30\u7bc0":{"freq":1,"weight":0.55}},{"\u9762\u5c0d":{"freq":2,"weight":1.39}},{"\u91d1\u7684":{"freq":1,"weight":2.54}},{"\u6c34\u707d":{"freq":1,"weight":-1.81}},{"\u5f71\u97ff":{"freq":1,"weight":2.02}},{"\u597d\u7684":{"freq":1,"weight":2.47}},{"\u6709\u4e9b":{"freq":1,"weight":0.11}},{"\u7d93\u904e":{"freq":1,"weight":0.28}},{"\u5b8c\u5584":{"freq":3,"weight":2.25}},{"\u8a31\u591a":{"freq":1,"weight":0.55}},{"\u8fb2\u4f5c\u7269":{"freq":1,"weight":0.98}},{"\u76f8\u7576":{"freq":1,"weight":2.75}},{"\u6c23\u5019":{"freq":2,"weight":2.37}},{"\u6642\u4ee3":{"freq":1,"weight":0.31}},{"\u6c34\u4f4d":{"freq":1,"weight":1.61}},{"\u57fa\u790e":{"freq":1,"weight":2.51}},{"\u7d50\u675f":{"freq":1,"weight":-3.39}},{"\u5de5\u4f5c":{"freq":1,"weight":1.47}},{"\u5be6\u5730":{"freq":1,"weight":1.2}},{"\u6307\u51fa":{"freq":1,"weight":0.29}}]' 
                     WHERE sid        = 10030
                    ;`

**Comment by milo** [comment]
The possible proper calls are:
```php
$db->query('UPDATE articles SET score = %f', $score, ', score_detail = %s', $json, 'WHERE sid = %i', $sid);

# or
$db->query('UPDATE articles SET %a', [
    'score%f' => $score,  # the %f is optional
    'score_detail%s' => $json,  # the %s is optional
], 'WHERE sid = %i', $sid);

# or
$db->update('articles', [
    'score%f' => $score,
    'score_detail%s' => $json,
])->where('sid = %i', $sid)->execute();
```

If you are sure, that there cannot be SQL injection in a passed query, than call it in this way:
```php
$db->query('%SQL', $sqlCommand);
```

Otherwise, dibi tries to sanity whole query to prevent SQL injection.

**Comment by jerrychen1013** [comment]
Yap, milo's suggest works.
If only insert with string, dibi will try to inspect the string strictly.
This is good practice to prevent SQL injection.

Thank you.
