### ISSUE TITLE
Dibi\Connection interface

### ISSUE THREAD

**Issue by SendiMyrkr** [dg/dibi#244]
Hi,
i thinking about create interface for Dibi\Connection class. Is there some serious reason why it doesn't have yet?

**Comment by dg** [comment]
Why is it useful?

**Comment by SendiMyrkr** [comment]
eg. to do mocks of class. In unit test, thanks to final methods, is not possible make correct mock of it. 

But i'm thinking about two interfaces, eg. QueryBuilder and Connection, with own implementations and than use Dibi\Connection as proxy of them. Usualy i don't need connection methods when i work with dibi.

**Comment by dakorpar** [comment]
I'm using repository pattern, and repositories are the only part of my application that uses dibi, then I just mock repositories.

**Comment by dg** [comment]
Closed by #274
