### ISSUE TITLE
XSS attack protection in dibi

### ISSUE THREAD

**Issue by jerrychen1013** [dg/dibi#245]
* [x] enhancement
* version: 
    - PHP: 7.0.1
    - DB: SQL Server 2012 Standard Edition
    - OS: Windows Server 2012 Standard

### Description
XSS attack will insert js code via form submit or url, for form submit,
PDO's prepare doesn't protect XSS because inserts script in DB is accepted.
But I wonder whether dibi has any protection in XSS issue, 
Because insert script from form submit is success.
Is anyway to prevent XSS attack from dibi? 

### Steps To Reproduce
**Client side**
`
<input type="text" name="name" value="ken">
`
`
<input type="textarea" name="content'  value="<script>alert('hello world')</script>">
`

**Server side:**
`
$arr = ['name'=>$_POST['name'], 'content'=>$_POST['content]];
`
`
dibi::query('INSERT INTO table ', $arr);
`

**DB(success insert)**
name: ken
content: <script>alert('hello world')</script>

**Comment by dg** [comment]
Dibi is database library and has no XSS protection. It is up to you to protect your application.
