### ISSUE TITLE
Examples with Tracy will fail

### ISSUE THREAD

**Issue by eugeene** [dg/dibi#248]
- bug report? yes
- feature request? no
- version: 3.0.7

Tracy (2.4.6) fails in examples with error 

> Tracy\Debugger::dispatch() called after some output has been sent. Try Tracy\OutputDebugger to find where output started. 

### Steps To Reproduce
run examples that are using Tracy

**Comment by trix1210** [comment]
i have the same error - what is the solution? i never get the tracy bar ...
