### ISSUE TITLE
Add host to tracy panel

### ISSUE THREAD

**Issue by northys** [dg/dibi#250]
- bug report? no
- feature request? yes

### Description
Add host to tracy panel so developer can see which panel is for which connection. Also makes sense when using integration database instead of local one.

Will implement myself

**Comment by Northys** [comment]
![screen shot 2017-03-24 at 12 11 09](https://cloud.githubusercontent.com/assets/2878126/24291853/048a8468-108b-11e7-89c4-b5f580f02c86.png)
