### ISSUE TITLE
Dibi Exception constructor to pass previous exception to base Exception class constructor

### ISSUE THREAD

**Issue by czukowski** [dg/dibi#254]
- bug report? no
- feature request? yes

### Description
The proposed change is to allow Dibi Exception constructors to receive previous exception and pass it down to the base Exception class constructor. While at it, it could also pass the error code to the base class as well, unless it's not doing so for a reason.

### Rationale
Allowing previous exceptions could provide useful information if the error has occurred during the exception handling phase.

Example:

```php
try {
    $db->begin('savepoint');
    $db->command()->...
    ... // goes on for a while
    $db->commit('savepoint');
} catch (Dibi\Exception $e) {
    // If rollback throws exception, the information about the original exception is lost.
    $db->rollback('savepoint');
    throw $e;
}
```

Improvement:

```php
    // If rollback throws exception, the information about the original exception
    // is NOT lost this time.
    try {
        $db->rollback('savepoint');
    } catch (Dibi\Exception $ex) {
        // This part is kind of awkward, because I have to throw a duplicate of the
        // 2nd exception as I can't just attach a previous exception to it. But at least
        // it will be possible to trace the problem back to the original exception.
        // Maybe this could be done better.
        throw new Dibi\Exception($ex->getMessage(), $ex->getCode(), $ex->getSql(), $e);
    }
    throw $e;
```

Why not throw just some standard PHP exception? It is, of course, possible, but the calling code could be also catching Dibi exceptions for its own purposes and it would be inconvenient to specially make it support a 'disguised' Dibi exception.

**Comment by dg** [comment]
Sounds good, can you send PR?
