### ISSUE TITLE
BUG: Error in examples

### ISSUE THREAD

**Issue by khamyl** [dg/dibi#258]
BUG
- version: 3.1.0

### Description
I'm getting warnings and fatal error error when trying to run example.

- Warning: Class 'Dibi\Connection' not found in ...\test\src\loader.php on line 65
- Warning: Class 'Dibi\DateTime' not found in ...\test\src\loader.php on line 65
- ...
- Warning: Class 'Dibi\Driver' not found in ...\test\src\loader.php on line 65
- Fatal error: Uncaught Error: Class 'dibi' not found in ...\test\examples\connecting-to-databases.php on line 13

### Steps To Reproduce
1. I created `test` folder in the document root of Apache server
2. Unpacked the `dibi-3.1.0.zip` in that folder
3. Run the following request: http://localhost/test/examples/connecting-to-databases.php

**Comment by dg** [comment]
I reverted it, so in last ZIP examples should work

**Comment by khamyl** [comment]
It trully works now. I use the minified version, so I don't need the composer. Thank you for a really quick fix.
