### ISSUE TITLE
fetch to return NULL instead of FALSE

### ISSUE THREAD

**Issue by dakorpar** [dg/dibi#266]
- bug report? no
- feature request? yes

### Description
It would be nice if fetch function returns NULL when nothing is found instead of FALSE.
It's breaking change so that's why I'm not creating PR but creating issue instead.
I think it would be usefull becaue then it would be possible to set in result directly to ?TableEntity

for example:

```
public function getUser($id) : ?UserEntity
{
             $result $this->dibi->select('*')
			->from('users')
			->where('id=%i', $id)
			->execute()
			->setRowClass(UserEntity::class)
			->fetch();
            return $result
}
```

**Comment by dg** [comment]
7d42317279c4cdbd6936d647bc44bf71484d4a97
