### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by dayvee** [dg/dibi#268]
Hi, this is a feature for auto json_decode on MySQL JSON columns.

Result.php (function normalize)
`#530   } elseif ($type === Type::JSON) {`
`#531   $row[$key] = json_decode($value) ?: $value;`

Type.php (const)
`#23   JSON = 'json',`

Helpers.php (function detectType)
`#194   'JSON' => Type::JSON,`

Cheers :)

**Comment by dg** [comment]
Can you send pull request?

**Comment by dayvee** [comment]
Sure, sorry, I'm new to GitHub.
