### ISSUE TITLE
Microsecond DateTime precision with Firebird 3

### ISSUE THREAD

**Issue by jahudka** [dg/dibi#273]
Bug report for version 3.1.0.

### Description
The Firebird driver formats full date & time with microsecond precision, but this results in a conversion error when run against a Firebird 3.0.1 server. `TIMESTAMP` in Firebird Dialect 3 (which itself is equivalent to `DATE` in Dialect 1) only supports _decimillisecond_ resolution (10e-4).

### Steps To Reproduce
1. Connect to any Firebird 3 database
2. `$connection->query('SELECT TIMESTAMP %dt AS [t] FROM RDB$DATABASE', new \DateTime());`

**Comment by dg** [comment]
Can you fix it and send a PR?
