### ISSUE TITLE
Select only one column with Fluent

### ISSUE THREAD

**Issue by BigOHenry** [dg/dibi#281]
- bug report? maybe
- feature request? no
- version: 3.2.0 

### Description
How to select one column with Dibi Fluent? When i use this code:
```
$this->db
->select("column")
->from("table");
```
I always got this kind of sql:
`SELECT 'column' FROM table;`
The result is string `column`.

I have to use this:
```
$this->db
->select("column as column")
->from("table");
```

**Comment by dg** [comment]
I am unable to reproduce it.

```php
try {
	$this->db->select("column")->from("table")->fetchSingle();
} catch (Exception $e) {
}

echo dibi::$sql;
// prints  SELECT [column] FROM [table] LIMIT 1
```

**Comment by BigOHenry** [comment]
I finally found case when its happening:
```
$this->db
            ->select("column")
            ->from("table")
            ->where("value = ?", 4);
```
In `where` is a column with name `value` (keyword), then it will create this sql:

`SELECT 'column' FROM table WHERE value = 4;`

**Comment by dg** [comment]
Still I am unable to reproduce it:

```php
try {
	$this->db->select("column")->from("table")->where("value = ?", 4)->fetchSingle();
} catch (Exception $e) {
}

echo dibi::$sql;
// prints  SELECT [column] FROM [table] WHERE value = 4 LIMIT 1
```

**Comment by BigOHenry** [comment]
Intereting. Did you try it on Postgre?

**Comment by dg** [comment]
It is tested with nearly all databases. 

Can you paste here your complete code?

**Comment by milo** [comment]
@BigOHenry Tested with PostgreSQL 9.6 and 10 and the translation is correct.
```php
$db
	->select("column")
	->from("table")
	->where("value = ?", 4)
	->test();
```
```
SELECT "column"
FROM "table"
WHERE value = 4
```

You have a next difference in output. Missing quotes around `table`.

Don't you pass Fluent somewhere else to `%ex` or `%sql` modifiers? If so, you should use `%SQL`, not escaping variant. A serialized Fluent is already sanitized.
