### ISSUE TITLE
ResultDriver::unescapeBinary() has too restrictive typehint

### ISSUE THREAD

**Issue by jiripudil** [dg/dibi#283]
- bug report? yes
- feature request? no
- version: 4.0.0-RC2

### Description

The typehint in `Dibi\ResultDriver::unescapeBinary(string $value)` seems too narrow. PDO wraps retrieved binary data in a resource and therefore we get:

```
Type error: Argument 1 passed to Dibi\Drivers\PdoDriver::unescapeBinary() must be of the type string, resource given, called in vendor/dibi/dibi/src/Dibi/Result.php on line 504 in vendor/dibi/dibi/src/Dibi/Drivers/PdoDriver.php:365
```

**Comment by dg** [comment]
Thanks for report
