### ISSUE TITLE
Huge BC break for fetchAssoc and fetchPairs

### ISSUE THREAD

**Issue by SendiMyrkr** [dg/dibi#284]
- bug report? yes
- feature request? no
- version: 4.0.0-RC2

### Description
At least fetchAssoc and fetchPairs ignores setResult, following example works for dibi 3, dibi 4 throws "Unknown column 'playerId' in associative descriptor"

### Steps To Reproduce
```php
$q = dibi::select('player_id')->from('players');

$q->setupResult('setRowFactory', function(array $row) {
    $line = new \stdClass();
    $line->playerId = $row['player_id'];

    return $line;
});

print_r($q->fetchAssoc('playerId'));
print_r($q->fetchPairs('playerId', 'playerId'));
```

**Comment by dg** [comment]
Yes, there is actually a BC break here. I did not expect anyone to use RowFactory in this way.
