### ISSUE TITLE
Releases 3.2.0 and 3.2.1 do not have minified version

### ISSUE THREAD

**Issue by C0rn3j** [dg/dibi#288]
https://github.com/dg/dibi/releases

Going off the .zip files in here, the last version to contain the minified folder/file is 3.1.1, and I see no mention of it being removed in the 3.2.0 release notes.

Is this intentional? If yes, why, and could the explanation be added to README.MD? searching for "mini" in it brings no results.

**Comment by dg** [comment]
Fixed

**Comment by C0rn3j** [comment]
Thanks a lot!

**Comment by dg** [comment]
However, since version 4 there will no longer be a minified version.
