### ISSUE TITLE
Cant use fetchAssoc on array row

### ISSUE THREAD

**Issue by josberger** [dg/dibi#308]
Version: 4.0.0

### Bug Description
When I use array as return from fetch a cant use fetchAssoc beacause it throw an exception. 

### Steps To Reproduce
$result->setRowClass("");
$result->fetchAssoc($keyColumn);

### Expected Behavior
Return associative tree

### Possible Solution
Add condition `&& !array_key_exists( $as, $row)` in the Result.php on line 249.

**Comment by dg** [comment]
Would you be able to send a pull request with a test?

**Comment by josberger** [comment]
Sorry now its work, its seem that I had a bug in my code.
