### ISSUE TITLE
Class 'Dibi\NotNullConstraintViolationException' not foun

### ISSUE THREAD

**Issue by czlukasss** [dg/dibi#310]
Version: 3.2.2

### Bug Description
**Class 'Dibi\NotNullConstraintViolationException' not found**
Is possible that this class is missing in .phar package? I am updating from v2 and this is only problem, which i see.
Thanks!

ErrorException #01
message protected => "Class 'Dibi\NotNullConstraintViolationException' not found"
string private => ""
code protected => 0
file protected => "phar:///xxxxxxx/dibi/3.2.2/dibi.phar/Dibi/Drivers/MySqliDriver.php"
line protected => 43
trace private => array (1)
0 => array (4)
function => "shutdownHandler"
class => "Tracy\Debugger"
type => "::"
args => array () [ ... ]
previous private => null
severity protected => 1

**Comment by dg** [comment]
fixed

**Comment by czlukasss** [comment]
Thanks, supposed, that in .phar will be this fix in future relases?

**Comment by dg** [comment]
Exactly.
