### ISSUE TITLE
Number expected

### ISSUE THREAD

**Issue by czlukasss** [dg/dibi#311]
Version: 3.2.2

Ahoj Davide, 
narazil jsem po update z v2 na ještě jeden zádrhel - moje aplikace často spoléhá na vnitřní modifikaci stringu v dotazu pomocí %i. Vím, že je to problematické, ale v 3 místo převedení do int hodí exception a na různých místech to dělá nečekané problémy - je jich více a je složité je dohledávat.

Neexistuje možnost jak např. configem nastavit staré chování, které mi přišlo lepší? Tedy když dostane dibi string, pochopí, že díky modifikátoru %i si ho převede na číslo?

Díky!

**Comment by dg** [comment]
Na to přepínač není, asi by bylo nejjednodušší nahradit `... val = %i', $i, ...` za `... val = %i', (int) $i, ...` nebo použít 3.0, která tuhle kontrolu nemá.

**Comment by czlukasss** [comment]
Jojo, takto to prioritně řeším. Nedá se nic dělat, zkouším si nastavit Tracy aby mě případně u těchto chyb notifikovala mejlem, tak snad se to podaří během dne odladit vše, na nižší verzi už se mi nechce :)

Díky

**Comment by dg** [comment]
Tak si v kodu natvrdo přepiš `throw new Exception` za `trigger_error()`, ať ti to nezabíjí aplikaci, a pak to po nějaké době všechno vychytáš.

V jakých případech se ti vlastně stává, že máš v řetězci něco, co není číslo?

**Comment by czlukasss** [comment]
Jelikož jedu na .phar, tak to je komplikované, ale myslím, že těch chyb už tam moc nebude, jestli vůbec nějaké.

Stává se to např. při filtru zboží v eshopu, když zákazník vyplní, že chce  CENU VĚTŠÍ NEŽ, a do té hodnoty dá desetinnou tečku nebo čárku. To je přesně ten případ, kdy jsme nechal dibi aby si to vyřešilo modifikátorem samo.
