### ISSUE TITLE
Problem with select float in E-notation format

### ISSUE THREAD

**Issue by chrudosvorlicek** [dg/dibi#317]
Version: I'm using v3.2.3, but it is also in master

### Bug Description
When selecting float number in e-notation (e.g. 1.1e+10) class \Dibi\Result rtrims the zero, which causes change of output value (1.1e+10 is selected as 1.1e+1).

### Steps To Reproduce
just try to select float number in e-notation from database.

### Expected Behavior
If the number is in e-notation, leave rigth zeros.

### Possible Solution
In class \Dibi\Result in private function normalize in part where $type === Type::FLOAT add check if number is in e-notation format and if it is, do not perform rtrim on zeros. It can be something like this: 
`$p = strpos($value, '.');
$e = strpos($value, 'e');
if ($p !== false && $e === false) {
    $value = rtrim(rtrim($value, '0'), '.');
} elseif ($p !== false && $e !== false) {
     $value = rtrim($value, '.');
}`

**Comment by dg** [comment]
Can you send pull request?

**Comment by chrudosvorlicek** [comment]
If suggested solution is ok for you, I can do it.

**Comment by dg** [comment]
I think it is ok.
