### ISSUE TITLE
Fluent::setupResult(): what is expected typehint?

### ISSUE THREAD

**Issue by jkuchar** [dg/dibi#325]
Version: dev-master

https://github.com/dg/dibi/blob/c8dfb1f8635a88c0210ab856c8ed176bf2b9f69e/src/Dibi/Fluent.php#L272

What about case when one use callable?
```php
$fluent->setupResult(function(Result $result) {$result->setRowClass(...);});
```

Should I change this to callable?

**Comment by dg** [comment]
It works? It should not.

**Comment by jkuchar** [comment]
Actually, no. I just thought it would be used like this.

**Comment by jkuchar** [comment]
Basically I misunderstand what this method is for (and I still quite not get it...)

**Comment by JanTvrdik** [comment]
The signature may be changed to `public function setupResult(string $method, ...$arguments): self` to make it slightly more obvious.
