### ISSUE TITLE
DROP DATABASE %n generates wrong result for database name containing period

### ISSUE THREAD

**Issue by medhi** [dg/dibi#329]
Version: 4.0.2

### Bug Description
I have a database called `my.database`  (contains period in its name). Unfortunately 
```
DROP DATABASE %n
``` 
generates 
```
DROP DATABASE `my`.`database`
```
And 
```
DROP DATABASE %s
``` 
generates 
```
DROP DATABASE 'my.database'
```
### Steps To Reproduce
```
dibi::test("DROP DATABASE %n", "my.database");
```

### Expected Behavior
Should generate
```
DROP DATABASE `my.database`
```

**Comment by milo** [comment]
PostgreSQL (and SQLServer and Oracle) has schemas and `"my"."database"` is correct, because `my` is schema name.

Try modifier `%N`.

**Comment by medhi** [comment]
Thanks, `%N` works, but I can't be found in any documentation. Should I create PR? But I am not sure if my explanation in documentation would be the best.

**Comment by dg** [comment]
@medhi It will definitely be better than none.

**Comment by medhi** [comment]
OK, but what I am able to read from the source code, `%N` is not supposed for database names, but for aliases. `%n AS %N`. But it probably works with database names because of the same syntax, is that right?

**Comment by dg** [comment]
I think the only difference is in meaning of the dot.
