### ISSUE TITLE
Empty arrays with (NOT) IN operator

### ISSUE THREAD

**Issue by adawolfa** [dg/dibi#337]
Hello,

currently, following query is translated like this, in case the corresponding argument is an empty array:

~~~
SELECT * FROM [table] WHERE %and;
SELECT * FROM [table] WHERE 1=1;
~~~

While this query with the same argument results in this:

~~~
SELECT * FROM [table] WHERE id IN (?);
SELECT * FROM [table] WHERE id IN ();
~~~

Which, obviously, fails. Now I realize this isn't exactly the same thing and I know a condition can solve this. Still, this is like the most common error I encounter.

I was thinking about translating it like this:

~~~
SELECT * FROM [table] WHERE 1 = 0; -- IN (?)
SELECT * FROM [table] WHERE 1 = 1; -- NOT IN (?)
~~~

I would consider such behavior correct, but there might be something I'm missing, for sure. I'm not certain it's always possible to do such replacement, as a more complicated expression can be used instead of a single column (like a sub-query).

I wouldn't suggest this if I could hook the translator, but there's no nice way to do it, as it's final (which is reasonable, I suppose).

What do you think?

**Comment by janpecha** [comment]
Why don't you use `SELECT * FROM [table] WHERE id IN %in;`?

**Comment by adawolfa** [comment]
Oops, overlooked the `%in` does that; using `?` quite often as that works with PDO and other libraries. Thanks.

So I assume the only problematic thing is the `NOT IN (NULL)`, which makes the query return no rows, instead of all rows. But, I've been looking at the translator and I think it's not possible to replace such expression with `1=1` or remove it completely, at least not without complicated parsing of the pattern.

I'll stick with a condition on that one, it's not that frequently used anyway.
