### ISSUE TITLE
Reuse postgres connection by default

### ISSUE THREAD

**Issue by groupnet** [dg/dibi#353]
This is a follow up to bugfix #349 (breaking change).

**Intention**
To be inline with the default behavior of `pg-connect(...)`, make the connection without `PGSQL_CONNECT_FORCE_NEW` by default (see PHP manual: [pg-connect](https://www.php.net/manual/en/function.pg-connect.php)). This might increase performance on frequent re-connections.

**Straight forward approach**
https://github.com/dg/dibi/compare/master...groupnet:PostgreDriver_persistent_bydefault

**Question**
To avoid confusion with the **persistent** postgres connection via the php function 'pg_**p**connect(...)' (see PHP manual: [pg-pconnect](https://www.php.net/manual/en/function.pg-pconnect.php)), I wanted to ask if you prefer to add new dibi parameter, eg. `forcenew` instead of using the existing parameter `persistent` as suggested in the approach above.

If no: I will make a pull request with the above approach.
If yes:
- what should be the name of the new parameter? `forcenew`?
- do you want me to implement another if-clause to also cover the **persistent** connection via `pg_pconnect(...)`?

**Comment by dg** [comment]
That would be good if someone using PostgreSQL can comment…

Because I don't care. I just don't want to listen to complaints that something has broken :-)

**Comment by groupnet** [comment]
The pull request #370 is my new approach to this issue:
- non-breaking change
- still gives the user to switch to PHP default: `config['connect_type'] = 0;`
