### ISSUE TITLE
sql query - created column

### ISSUE THREAD

**Issue by davidgithub1980** [dg/dibi#355]
Hi. I seem to have a simple issue. My test query:

`'SELECT col1, col2, created, col3 from table';`

works only when the _created_ column is removed. It appears to be a reserved word or something like that. Altering it does not help. The following does not work too:

```
'SELECT col1, col2, created as c, col3 from table';
'SELECT col1, col2, \'created\', col3 from table';
```

How can th existing db column can be extraczed?

**Comment by dg** [comment]
try `[created]`
