### ISSUE TITLE
fetchAssoc can't handle date(time) column type

### ISSUE THREAD

**Issue by MartinStepar** [dg/dibi#359]
Version: 4.1.2

### Bug Description
Method **fetchAssoc** uses internally method **normalize**. **Normalize** converts date value to object `Dibi\DateTime`. After that normalizing fails with PHP error message *"Illegal offset type"*, because method **fetchAssoc** tries to use `Dibi\DateTime` object as array key.

### Steps To Reproduce
```
$db->query('
	SELECT place_id, day, COUNT(product_id) AS dayCount
	FROM last_locations
	GROUP BY place_id, day
')->fetchAssoc('place_id|day');
```

### Expected Behavior
Method should probably use `$this->types` (maybe with `$this->formats`) and convert normalized value into string for array key purpose.

### Possible Solution
Maybe put here: https://github.com/dg/dibi/blob/master/src/Dibi/Result.php#L285 something like that (simple example without `$this->formats`):
```
$type = isset($this->types[$as]) ? $this->types[$as] : NULL;
if ($type === Type::DATE) {
	$key = ($row->$as)->format('Y-m-d');

} elseif ($type === Type::DATETIME) {
		$key = ($row->$as)->format('Y-m-d H:i:s');

} else {
	$key = $row->$as;
}

$x = &$x[$key];
```

**Comment by dg** [comment]
Unfortunately, this cannot be solved in the way you suggest for backward compatibility.

**Comment by MartinStepar** [comment]
Thanks for fixing this bug. Casting to string is good enough =)
