### ISSUE TITLE
Tracy\Panel: show connection info of event

### ISSUE THREAD

**Issue by zdenekzahor** [dg/dibi#365]
Why was connection info of events removed from panel (https://github.com/dg/dibi/commit/ae6c8756b67496a06c71af912bacaf7ca97c5fc3)? With multiple connections showing connection info (panel header) of last event doesn't make sense.

**Comment by dg** [comment]
Are you using one panel for multiple connections?

**Comment by zdenekzahor** [comment]
> Are you using one panel for multiple connections?

Yes (result with patch; extra column "Connection" + no info in header):
![Snímek obrazovky pořízený 2020-06-05 15-20-27](https://user-images.githubusercontent.com/26121211/83882238-204fc400-a742-11ea-8b85-af992eaa50cf.png)

This style will be applied only for panels with multiple connections. Panels with only one connection => no extra column "Connection" + info in header. (?)
