### ISSUE TITLE
Possibility to override more Types through __construct($config) string

### ISSUE THREAD

**Issue by Ejsstiil** [dg/dibi#367]
We can change only few types for normalize() behaviour.
JSON, DATE, DATETIME
like here:
https://github.com/dg/dibi/blob/70e940ffde517b603ba5003956a115b07193e4cf/src/Dibi/Connection.php#L64-L65

- Current problem

We don't have access to modify behaviour for the rest - namely for TIME and TIME_INTERVAL. 
1. MariaDB's TIME column become \DateInterval which is the problem i currently have.
This block is hit even when column native type is "TIME":
https://github.com/dg/dibi/blob/70e940ffde517b603ba5003956a115b07193e4cf/src/Dibi/Result.php#L493-L496
2. Also its not possible to call ->setFormat() or ->setType() when you using \Fluent unlike here:
https://github.com/dg/dibi/blob/70e940ffde517b603ba5003956a115b07193e4cf/examples/result-set-data-types.php#L26-L33

- Explain your intentions.

1. As title says - to able these to configure (or suppress) via constructor $config string.
Add TIME and TIME_INTERVAL to configurable parameters and allow to set them to `'s', // as 'string'` to keep column as is.
```php
	'lazy'     => '1',
	'charset'  => 'utf8',
	'result'   => ['formatDate' => 'Y-m-d', 'formatDateTime' => 'Y-m-d H:i:s', 'formatJson' => 'string', 
'formatTime' => 'string', 'formatTimeInterval' => 'string']
```
https://github.com/dg/dibi/blob/70e940ffde517b603ba5003956a115b07193e4cf/src/Dibi/Type.php#L27-L28
2. Maybe some another flag to disable normalizer() along with detectTypes() completellly
https://github.com/dg/dibi/blob/70e940ffde517b603ba5003956a115b07193e4cf/src/Dibi/Result.php#L435
and
https://github.com/dg/dibi/blob/70e940ffde517b603ba5003956a115b07193e4cf/src/Dibi/Result.php#L450

- It's up to you to make a strong case to convince the project's developers of the merits of this feature.
Not in every environment such auto-re-typing to PHP's types is useful and to conform the freedom Ill suggest this change.

**Comment by Ejsstiil** [comment]
Any comment on this?

**Comment by dg** [comment]
I added options `result > normalize` to disable normalize, `result > formatTimeInterval` to affect interval format and option value 'native' to leave value as is.
