### ISSUE TITLE
Inserting a DateInterval

### ISSUE THREAD

**Issue by LHavlicek** [dg/dibi#368]
Version: 4.1.3

MySQL database. Attempting to insert a DateInterval that is used for the TIME_INTERVAL type fails. The error is probably on line 311 in the Drivers/MySqliDriver.php file (https://github.com/dg/dibi/blob/70e940ffde517b603ba5003956a115b07193e4cf/src/Dibi/Drivers/MySqliDriver.php#L311), where quotation marks are missing.

Tests for working with DateInterval may also be missing, so the error escaped attention.

**Comment by dg** [comment]
Can you send pull request?

**Comment by LHavlicek** [comment]
I will try to.
