### ISSUE TITLE
ARRAY[...] expression raises syntax error because of Translation

### ISSUE THREAD

**Issue by groupnet** [dg/dibi#374]
Version: 4.1.3

### Bug Description
An `Uncaught Dibi\\DriverException: syntax error ...` is raised, when selecting a simple `ARRAY[...]` in [Postgresql](https://www.postgresql.org/docs/12/functions-array.html).

The expression `ARRAY[1,2]` is translated to `ARRAY "1,2"` I guess by this regex: https://github.com/dg/dibi/blob/ff1c9fa860bad401664a82501ec5e64776892f54/src/Dibi/Translator.php#L109

### Steps To Reproduce
```
$database->query('SELECT ARRAY[1,2]');
```

### Expected Behavior
No translation of `ARRAY[...]` expressions

### Possible Solution
Couldn't solve it. Quick'n'dirty workaround is to remove the square bracket `[` from line 89, to skip translation:
https://github.com/dg/dibi/blob/ff1c9fa860bad401664a82501ec5e64776892f54/src/Dibi/Translator.php#L89

**Comment by janpecha** [comment]
Try use `%SQL` modifier or `$connection->literal('ARRAY[1,2]')`.

**Comment by groupnet** [comment]
Works - thanks for the help!
