### ISSUE TITLE
getAffectedRows isnt working

### ISSUE THREAD

**Issue by theboardio** [dg/dibi#377]
Version: 4.1.3

### Bug Description

Example from readme:

$database->query('UPDATE users SET', [
	'name' => $name,
	'year' => $year,
], 'WHERE id = ?', $id);
// UPDATE users SET `name` = 'Jim', `year` = 1978 WHERE id = 123

// returns the number of updated rows
$affectedRows = $database->getAffectedRows();

Got logicexception:

LogicException Call to undefined method Dibi\Result::getAffectedRows(). 
    /var/www/data/src/vendor/dibi/dibi/src/Dibi/Strict.php:35 Dibi\Result::__call
    /var/www/data/src/functions/billing_functions.php:61 stripe_check_paymentmethod
    /var/www/data/public/user/payments.php:12 [main]

### Expected Behavior
getAffectedRows() should report 1 or 0

**Comment by eydun** [comment]
What database driver are you using?

**Comment by theboardio** [comment]
Hello, Im using mysqli with this config example:

dibi::connect([
    'driver'   => 'mysqli',
    'host'     => 'localhost',
    'username' => 'root',
    'password' => '***',
    'database' => 'test',
    'charset'  => 'utf8',
]);

**Comment by eydun** [comment]
Try connecting like this:
```
$database = new Dibi\Connection([
    'driver'   => 'mysqli',
    'host'     => 'localhost',
    'username' => 'root',
    'password' => '***',
    'database' => 'test',
    'charset'  => 'utf8'
]);
```

**Comment by theboardio** [comment]
I didnt tested using your way but i cant change it because i need to change
a lot of code in the php project

**Comment by dg** [comment]
You are calling getAffectedRows on result set, no on $database
