### ISSUE TITLE
 Class dibi case

### ISSUE THREAD

**Issue by zabous** [dg/dibi#384]
Why is class name "dibi" lowercase?
All other sub classes (Dibi\Connection, Dibi\Row, Dibi\Result, Dibi\Fluent,... ) are first upper case?
Do you plan to change it?
Thanks...

**Comment by blavka** [comment]
I also encountered this problem. When I used downloaded phar from release.

My quick fix:

```
require_once 'phar://' . LIBS_PATH . '/dibi.phar';
require_once 'phar://' . LIBS_PATH . '/dibi.phar/Dibi/dibi.php';

```

**Comment by dg** [comment]
It's just the way it is historically.
