### ISSUE TITLE
Replace Literal with Stringable

### ISSUE THREAD

**Issue by dakujem** [dg/dibi#386]
As well as `Expression` ( see #385 ), `Literal` should also be made into an interface, but the situation is less optimal.

It could be replaced using the new `Stringable` interface in PHP 8.

`$value instanceof Literal || $value instanceof Stringable` could be used here, which could be forward and back compatible and easy to implement.

**Comment by milo** [comment]
This is dangerous. Literal means SQL literal, so already escaped string. Stringable means that object can be converted to string.

**Comment by dakujem** [comment]
Good point. A separate interface would do then.
