### ISSUE TITLE
SqlsrvDriver.php at line 73 - Warning: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by zabous** [dg/dibi#392]
SqlsrvDriver.php in Dibi\Drivers\SqlsrvDriver::__construct at line 73
$info[0]['message'] in simetimes null

https://github.com/dg/dibi/blob/c3b365e59986662633219708e5f0e5a894c5925d/src/Dibi/Drivers/SqlsrvDriver.php#L70

**Comment by gabema** [comment]
I've seen this issue as well. What type of SQL Server DB are you attempting to connect to? SQL Server (version?), SQL Express (Version?), Azure SQL?

**Comment by gabema** [comment]
Also helpful to know would be php version and architecure and sql driver extensions you are using TS vs NTS.

**Comment by zabous** [comment]
I attempt to SQL Server 2019 (version 15.0.4053.23)
I use PHP 8.0.7 on Alpine Linux (amd64) with MS SQL TOOLS v.17.7.1.1-1
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15#alpine17
