### ISSUE TITLE
result->free, mysqli_result object is already closed

### ISSUE THREAD

**Issue by petrf89** [dg/dibi#439]
Version
dibi : 4.2.7.
php: 8.2
nette/appliction: 3.1.11
nette/bootstrap: 3.2

### Bug Description
... mysqli_result object is already closed , when public method free is called

### Steps To Reproduce
```
$result = dibi::query('select * from any_table');
$result->free();
```
![obrazek](https://github.com/dg/dibi/assets/5654763/410e7017-bd0f-4779-af35-4701172fbc3e)

### Expected Behavior
no error raised

**Comment by dg** [comment]
fixed
