### ISSUE TITLE
Firebird Support

### ISSUE THREAD

**Issue by ondrej-tuhacek** [dg/dibi#91]
Hello,

I have a problem with Dibi Firebird Driver using LIMIT and OFFSET (which should be FIRST and SKIP on FB). Dibi Firebird driver is not using its applyLimit.

When I create a query using DibiFluent interface like this:

	$query = $dibiConnection->select('*')->from('table')->limit(10)->offset(0);

and then run it:

	foreach($query ...) { ... }

It constructs the query like:

	SELECT * FROM table LIMIT 10 OFFSET 0

but it should be:

	SELECT FIRST 10 SKIP 0 * FROM table

I made a QuickFix for it in DibiTranslator.php

	/**
	 * Generates SQL.
	 * @param  array
	 * @return string
	 * @throws DibiException
	 */
	public function translate(array $args)
	{
		$this->identifiers = new DibiHashMap(array($this, 'delimite'));
		$this->driver = $this->connection->getDriver();

		$args = array_values($args);
		while (count($args) === 1 && is_array($args[0])) { // implicit array expansion
			$args = array_values($args[0]);
		}
		
	// ---- FIX STARTS HERE ----
		foreach($args as $index => $value)
		{
			if($value === 'LIMIT') $args[$index] = '%lmt';
			if($value === 'OFFSET') $args[$index] = '%ofs';
		}
	// ---- FIX ENDS HERE ----

		$this->args = $args;

I'm not sure whether this is a good solution?

One more final note:

When I create the same query using:

	$dibiConnection->select('*')->from('table')->fetchAll(0,10);

it constructs the query successfully with FIRST and SKIP because of %lmt and %ofs being filled by calling:

	fetchAll(0, 10).

**Comment by bckp** [comment]
This should be closed, as it is already solved...

**Comment by ondrej-tuhacek** [comment]
OK, Thanks
